#!/bin/bash

if [ ! -f liquidc ]; then
  git clone /git/liquidc.git
fi

cd liquidc
./cleanup
./init-submodules.sh -local
git checkout $@
git submodule update
./configure

if [ $? ]; then
  exit 1;
fi

./build.sh

exit $?
