/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef unsigned int size_t;
typedef long long __quad_t;
typedef long __off_t;
typedef __quad_t __off64_t;
struct _IO_FILE;
typedef struct _IO_FILE FILE;
typedef __builtin_va_list __gnuc_va_list;
typedef void _IO_lock_t;
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15U * sizeof(int ) - 4U * sizeof(void *)) - sizeof(size_t )] ;
};
typedef struct _IO_FILE _IO_FILE;
struct hash_entry {
   unsigned int key ;
   void *entry ;
   struct hash_entry *next ;
   unsigned int padding ;
};
typedef struct hash_entry *HashEntry;
struct hash {
   HashEntry *array ;
   int (*mapfunc)(unsigned int  ) ;
   int size ;
   unsigned int padding ;
};
typedef struct hash *Hash;
struct vert_st {
   int mindist ;
   struct vert_st *next ;
   Hash edgehash ;
   unsigned int padding ;
};
typedef struct vert_st *Vertex;
struct graph_st {
   Vertex vlist ;
};
typedef struct graph_st *Graph;
struct blue_return {
   Vertex vert ;
   int dist ;
};
typedef struct blue_return BlueReturn;
typedef __gnuc_va_list va_list;
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   unsigned int __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned int  , char const   *  , ...) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned int  , int  , unsigned int  , char const   * 
                                , ...) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned int  , int  , unsigned int  , char const   * ,
                                 __builtin_va_list  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
__inline extern  __attribute__((__nothrow__)) void *( __attribute__((__always_inline__)) memset)(void *__dest ,
                                                                                                 int __ch ,
                                                                                                 size_t __len )  __attribute__((__nonnull__(1))) ;
__inline extern  __attribute__((__nothrow__)) int atoi(char const   *__nptr )  __attribute__((__warn_unused_result__,
__pure__, __nonnull__(1))) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status ) ;

extern struct _IO_FILE *stdout ;
__inline extern int ( __attribute__((__always_inline__)) vfprintf)(FILE * __restrict  __stream ,
                                                                   char const   * __restrict  __fmt ,
                                                                   __gnuc_va_list __ap ) ;

void *HashLookup(unsigned int key , Hash hash ) ;
Graph MakeGraph(int numvert ) ;
void chatting(char *s  , ...) ;
/* static BlueReturn BlueRule(Vertex inserted , Vertex vlist )  */
/* { BlueReturn retval ; */
/*   Vertex tmp ; */
/*   Vertex prev ; */
/*   Hash hash ; */
/*   int dist ; */
/*   int dist2 ; */
/*   int count ; */
/*   void *tmp___0 ; */
/*   Vertex next ; */
/*   void *tmp___1 ; */

/*   { */
/*   if (! vlist) { */
/*     retval.dist = 999999; */
/*     return (retval); */
/*   } */
/*   prev = vlist; */
/*   retval.vert = vlist; */
/*   retval.dist = vlist->mindist; */
/*   hash = vlist->edgehash; */
/*   tmp___0 = HashLookup((unsigned int )inserted, hash); */
/*   dist = (int )tmp___0; */
/*   if (dist) { */
/*     if (dist < retval.dist) { */
/*       vlist->mindist = dist; */
/*       retval.dist = dist; */
/*     } */
/*   } else { */
/*     chatting((char *)"Not found\n"); */
/*   } */
/*   count = 0; */
/*   tmp = vlist->next; */
/*   while (tmp) { */
/*     count ++; */
/*     if ((unsigned int )tmp == (unsigned int )inserted) { */
/*       next = tmp->next; */
/*       prev->next = next; */
/*     } else { */
/*       hash = tmp->edgehash; */
/*       dist2 = tmp->mindist; */
/*       tmp___1 = HashLookup((unsigned int )inserted, hash); */
/*       dist = (int )tmp___1; */
/*       if (dist) { */
/*         if (dist < dist2) { */
/*           tmp->mindist = dist; */
/*           dist2 = dist; */
/*         } */
/*       } else { */
/*         chatting((char *)"Not found\n"); */
/*       } */
/*       if (dist2 < retval.dist) { */
/*         retval.vert = tmp; */
/*         retval.dist = dist2; */
/*       } */
/*     } */
/*     prev = tmp; */
/*     tmp = tmp->next; */
/*   } */
/*   return (retval); */
/* } */
/* } */
/* static Vertex MyVertexList  =    (Vertex )((void *)0); */
/* static int ComputeMst(Graph graph , int numvert )  */
/* { Vertex inserted ; */
/*   Vertex tmp ; */
/*   int cost ; */
/*   int dist ; */
/*   BlueReturn br ; */

/*   { */
/*   cost = 0; */
/*   chatting((char *)"Compute phase 1\n"); */
/*   inserted = graph->vlist; */
/*   tmp = inserted->next; */
/*   graph->vlist = tmp; */
/*   MyVertexList = tmp; */
/*   numvert --; */
/*   chatting((char *)"Compute phase 2\n"); */
/*   while (numvert) { */
/*     if ((unsigned int )inserted == (unsigned int )MyVertexList) { */
/*       MyVertexList = MyVertexList->next; */
/*     } */
/*     br = BlueRule(inserted, MyVertexList); */
/*     inserted = br.vert; */
/*     dist = br.dist; */
/*     numvert --; */
/*     cost += dist; */
/*   } */
/*   return (cost); */
/* } */
/* } */
/* int dealwithargs(int argc , char **argv ) ; */
/* int main(int argc , char **argv )  */
/* { Graph graph ; */
/*   int dist ; */
/*   int size ; */

/*   { */
/*   chatting((char *)"Hash entry size = %d\n", sizeof(struct hash_entry )); */
/*   chatting((char *)"Hash size = %d\n", sizeof(struct hash )); */
/*   chatting((char *)"Vertex size = %d\n", sizeof(struct vert_st )); */
/*   size = dealwithargs(argc, argv); */
/*   chatting((char *)"Making graph of size %d\n", size); */
/*   graph = MakeGraph(size); */
/*   chatting((char *)"Graph completed\n"); */
/*   chatting((char *)"About to compute mst \n"); */
/*   dist = ComputeMst(graph, size); */
/*   chatting((char *)"MST has cost %d\n", dist); */
/*   exit(0); */
/* } */
/* } */
/* extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__warn_unused_result__, */
/* __malloc__)) ; */
/* Hash MakeHash(int size , int (*map)(unsigned int  ) ) ; */
/* void HashInsert(void *entry , unsigned int key , Hash hash ) ; */
/* static int HashRange  ; */
int mult(int p , int q )
{ int p1 ;
  int p0 ;
  int q1 ;
  int q0 ;

  {
  p1 = p / 10000;
  p0 = p % 10000;
  q1 = q / 10000;
  q0 = q % 10000;
  return (((p0 * q1 + p1 * q0) % 10000) * 10000 + p0 * q0);
}
}
int mst_random(int seed )
{ int tmp ;
  int tmp___0 ;

  {
  tmp___0 = mult(seed, 31415821);
  tmp = tmp___0 + 1;
  return (tmp);
}
}
int compute_dist(int i , int j , int numvert )
{ int less ;
  int gt ;
  int tmp ;

  {
  if (i < j) {
    less = i;
    gt = j;
  } else {
    less = j;
    gt = i;
  }
  tmp = mst_random(less * numvert + gt);
  return (tmp % 2048 + 1);
}
}
int hashfunc(unsigned int key )
{
    // pmr: "inlined" from global, need to fix
    unsigned int HashRange = 100;

  {
  return ((int )((key >> 4) % (unsigned int )HashRange));
}
}
/* static void AddEdges(Graph retval , int numvert )  */
/* { Vertex src ; */
/*   Vertex dest ; */
/*   Hash hash ; */
/*   int i ; */
/*   int j ; */
/*   int dist ; */
/*   int num_inserted ; */

/*   { */
/*   num_inserted = 0; */
/*   j = 0; */
/*   while (j < numvert) { */
/*     src = retval->vlist + j; */
/*     hash = src->edgehash; */
/*     i = 0; */
/*     while (i < numvert) { */
/*       if (i != j) { */
/*         dist = compute_dist(i, j, numvert); */
/*         dest = retval->vlist + i; */
/*         HashInsert((void *)dist, (unsigned int )dest, hash); */
/*         num_inserted ++; */
/*       } */
/*       i ++; */
/*     } */
/*     j ++; */
/*   } */
/*   chatting((char *)"%d edges inserted\n", num_inserted); */
/*   return; */
/* } */
/* } */
/* Graph MakeGraph(int numvert )  */
/* { int i ; */
/*   Vertex vf ; */
/*   Vertex vt ; */
/*   Graph retval ; */
/*   void *tmp ; */
/*   void *tmp___0 ; */

/*   { */
/*   tmp = malloc(sizeof(*retval)); */
/*   retval = (struct graph_st *)tmp; */
/*   chatting((char *)"Make phase 1: Creating hash tables\n"); */
/*   tmp___0 = malloc((unsigned int )numvert * sizeof(*vf)); */
/*   retval->vlist = (struct vert_st *)tmp___0; */
/*   vt = (struct vert_st *)((void *)0); */
/*   i = numvert - 1; */
/*   while (i >= 0) { */
/*     vf = retval->vlist + i; */
/*     HashRange = numvert / 4; */
/*     vf->mindist = 9999999; */
/*     vf->edgehash = MakeHash(HashRange, & hashfunc); */
/*     vf->next = vt; */
/*     vt = vf; */
/*     i --; */
/*   } */
/*   chatting((char *)"Make phase 3: Creating graph\n"); */
/*   AddEdges(retval, numvert); */
/*   chatting((char *)"Make returning\n"); */
/*   return (retval); */
/* } */
/* } */
/* void HashDelete(unsigned int key , Hash hash ) ; */
/* static void *localmalloc(int size ) ; */
/* static int remaining  =    0; */
/* static char *temp  ; */
/* static void *localmalloc(int size )  */
/* { char *blah ; */
/*   void *tmp ; */

/*   { */
/*   if (size > remaining) { */
/*     tmp = malloc(32768U); */
/*     temp = (char *)tmp; */
/*     if (! temp) { */
/*       chatting((char *)"Error! malloc returns null\n"); */
/*     } */
/*     remaining = 32768; */
/*   } */
/*   blah = temp; */
/*   temp += size; */
/*   remaining -= size; */
/*   return ((void *)blah); */
/* } */
/* } */
/* Hash MakeHash(int size , int (*map)(unsigned int  ) )  */
/* { Hash retval ; */
/*   void *tmp ; */
/*   void *tmp___0 ; */

/*   { */
/*   tmp = localmalloc((int )sizeof(*retval)); */
/*   retval = (struct hash *)tmp; */
/*   retval->size = size; */
/*   tmp___0 = localmalloc((int )((unsigned int )size * sizeof(*(retval->array + 0)))); */
/*   retval->array = (HashEntry *)tmp___0; */
/*   memset((void *)((char *)retval->array), 0, (unsigned int )size * sizeof(*(retval->array + 0))); */
/*   retval->mapfunc = map; */
/*   retval->padding = 0U; */
/*   return (retval); */
/* } */
/* } */
/* void *HashLookup(unsigned int key , Hash hash )  */
/* { int j ; */
/*   HashEntry ent ; */

/*   { */
/*   j = (*(hash->mapfunc))(key); */
/*   ent = *(hash->array + j); */
/*   while (1) { */
/*     if (ent) { */
/*       if (! (ent->key != key)) { */
/*         break; */
/*       } */
/*     } else { */
/*       break; */
/*     } */
/*     ent = ent->next; */
/*   } */
/*   if (ent) { */
/*     return (ent->entry); */
/*   } */
/*   return ((void *)0); */
/* } */
/* } */
/* void HashInsert(void *entry , unsigned int key , Hash hash )  */
/* { HashEntry ent ; */
/*   int j ; */
/*   void *tmp ; */

/*   { */
/*   j = (*(hash->mapfunc))(key); */
/*   tmp = localmalloc((int )sizeof(*ent)); */
/*   ent = (struct hash_entry *)tmp; */
/*   ent->next = *(hash->array + j); */
/*   *(hash->array + j) = ent; */
/*   ent->key = key; */
/*   ent->entry = entry; */
/*   return; */
/* } */
/* } */
/* void HashDelete(unsigned int key , Hash hash )  */
/* { HashEntry *ent ; */
/*   HashEntry tmp ; */
/*   int j ; */

/*   { */
/*   j = (*(hash->mapfunc))(key); */
/*   ent = hash->array + j; */
/*   while (1) { */
/*     if (*ent) { */
/*       if (! ((*ent)->key != key)) { */
/*         break; */
/*       } */
/*     } else { */
/*       break; */
/*     } */
/*     ent = & (*ent)->next; */
/*   } */
/*   tmp = *ent; */
/*   *ent = (*ent)->next; */
/*   return; */
/* } */
/* } */
int dealwithargs(int argc , char **argv )
{ int level ;

  {
  if (argc > 1) {
      level = atoi((char const   *)*(argv + 1));
  } else {
    level = 1024;
  }
  return (level);
}
}
/* /\* compiler builtin:  */
/*    void __builtin_va_end(__builtin_va_list  ) ;  *\/ */
/* /\* compiler builtin:  */
/*    void __builtin_va_start(__builtin_va_list  ) ;  *\/ */
/* void chatting(char *s  , ...)  */
/* { va_list ap ; */

/*   { */
/*   __builtin_va_start(ap, s); */
/*   vfprintf((FILE * __restrict  )stdout, (char const   * __restrict  )s, ap); */
/*   __builtin_va_end(ap); */
/*   return; */
/* } */
/* } */
