/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

#line 1 "test0.c"
int main(void) 
{ int x ;

  {
#line 3
  x = 0;
#line 4
  if (x == 5) {
#line 5
    x += 1;
  } else {

  }
#line 7
  return (0);
}
}
